agenda:
  last_scrape:
    bellas_artes_san_fernando: &id001 2022-09-01
    caixa_forum_madrid: *id001
    casa_de_mexico: &id002 2022-09-02
    casa_de_mexico_expo: *id002
    casa_de_mexico_teatro: *id002
    centro_centro: *id001
    cine_golem: &id003 2022-09-02
    cine_paz: *id002
    cine_renoir_plaza: *id002
    cines_verdi: *id002
    cines_yelmo: *id003
    cinesa: *id003
    cinescallao: *id002
    cineteca_madrid: *id003
    circo_price: *id003
    circulo_bellas_artes: *id001
    clamores: *id002
    conde_duque_alberto: *id002
    conde_duque_santa: *id002
    corte_ingles: *id002
    fundacion_juan_march: *id001
    fundacion_maphre: *id001
    fundacion_telefonica: *id001
    honky_tonk: *id003
    infanta_isabel: *id003
    lazaro_galdiano: *id003
    luchana_kids: *id002
    maria_cristina: *id001
    museo_arqueologico: *id001
    museo_arte_contemporaneo: *id001
    museo_del_prado: *id001
    museo_nacional_de_ciencias_naturales: *id001
    museo_reina_sofia: *id001
    museo_sorolla: *id001
    museo_thyssen_bornemisza: *id001
    off_latina: *id003
    pequeno_teatro_gran_via: *id003
    sala_arte_canal_isabel_ii: *id003
    sala_azarte: *id003
    sala_berlanga: *id002
    sala_equis: *id001
    sala_mirador: *id003
    soho_club: *id003
    teatro_abadia: *id003
    teatro_alfil: *id003
    teatro_apolo: *id003
    teatro_arlequin_gv: *id003
    teatro_calderon: *id003
    teatro_capitol: *id003
    teatro_del_barrio: *id003
    teatro_edp_gran_via: *id003
    teatro_espanol_naves: *id003
    teatro_fernan_gomez: *id003
    teatro_figaro: *id003
    teatro_lara: *id003
    teatro_lara2: *id003
    teatro_luchana: *id002
    teatro_quique: *id002
    teatro_real: *id003
    teatro_reina_victoria: *id003
    teatros_canal: *id002
    wizink_center: *id003
  sitios:
  - cine_paz
  - cines_verdi
  - cinescallao
  - clamores
  - conde_duque_alberto
  - conde_duque_santa
  - corte_ingles
  - luchana_kids
  - sala_berlanga
  - teatro_luchana
  - teatro_quique
  - casa_de_mexico
  - casa_de_mexico_expo
  - casa_de_mexico_teatro
  - teatros_canal
  - cine_renoir_plaza
  - wizink_center
  - circo_price
  - soho_club
  - cinesa
  - teatro_abadia
  - honky_tonk
  - off_latina
  - teatro_lara
  - teatro_espanol_naves
  - infanta_isabel
  - teatro_fernan_gomez
  - teatro_alfil
  - teatro_apolo
  - teatro_calderon
  - teatro_del_barrio
  - sala_mirador
  - teatro_real
  - teatro_arlequin_gv
  - teatro_edp_gran_via
  - teatro_figaro
  - pequeno_teatro_gran_via
  - teatro_capitol
  - teatro_lara2
  - sala_azarte
  - teatro_reina_victoria
  - cine_golem
  - cines_yelmo
  - museo_sorolla
  - fundacion_telefonica
  - maria_cristina
  - fundacion_juan_march
  - museo_del_prado
  - museo_thyssen_bornemisza
  - museo_reina_sofia
  - caixa_forum_madrid
  - fundacion_maphre
  - circulo_bellas_artes
  - museo_arqueologico
  - museo_nacional_de_ciencias_naturales
  - museo_arte_contemporaneo
  - centro_centro
  - bellas_artes_san_fernando
  - sala_equis
  - cineteca_madrid
  - lazaro_galdiano
  - sala_arte_canal_isabel_ii
  time:
    bellas_artes_san_fernando: 7
    caixa_forum_madrid: 7
    casa_de_mexico: 0
    casa_de_mexico_expo: 0
    casa_de_mexico_teatro: 0
    centro_centro: 7
    cine_golem: 0
    cine_paz: 0
    cine_renoir_plaza: 0
    cines_verdi: 0
    cines_yelmo: 0
    cinesa: 0
    cinescallao: 0
    cineteca_madrid: 7
    circo_price: 0
    circulo_bellas_artes: 7
    clamores: 0
    conde_duque_alberto: 0
    conde_duque_santa: 0
    corte_ingles: 0
    fundacion_juan_march: 7
    fundacion_maphre: 7
    fundacion_telefonica: 7
    honky_tonk: 0
    infanta_isabel: 0
    lazaro_galdiano: 7
    luchana_kids: 0
    maria_cristina: 7
    museo_arqueologico: 7
    museo_arte_contemporaneo: 7
    museo_del_prado: 7
    museo_nacional_de_ciencias_naturales: 7
    museo_reina_sofia: 7
    museo_sorolla: 7
    museo_thyssen_bornemisza: 7
    off_latina: 0
    pequeno_teatro_gran_via: 0
    sala_arte_canal_isabel_ii: 7
    sala_azarte: 0
    sala_berlanga: 0
    sala_equis: 7
    sala_mirador: 0
    soho_club: 0
    teatro_abadia: 0
    teatro_alfil: 0
    teatro_apolo: 0
    teatro_arlequin_gv: 0
    teatro_calderon: 0
    teatro_capitol: 0
    teatro_del_barrio: 0
    teatro_edp_gran_via: 0
    teatro_espanol_naves: 0
    teatro_fernan_gomez: 0
    teatro_figaro: 0
    teatro_lara: 0
    teatro_lara2: 0
    teatro_luchana: 0
    teatro_quique: 0
    teatro_real: 0
    teatro_reina_victoria: 0
    teatros_canal: 0
    wizink_center: 0
